name: Compare APK
on:
  pull_request:
    branches:
      - dev
jobs:
  build-dev:
    name: Build master Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: dev
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17'
          channel: 'stable'
      - run: flutter pub get
      - run: |
            flutter build apk
            mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/app-master.apk
      - name: Upload master APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: build/app/outputs/apk/release/app-master.apk
  build-pr:
    name: Build PR Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.13+hotfix.9'
          channel: 'stable'
      - run: flutter pub get
      - run: |
            flutter build apk
            mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/app-pr.apk
      - name: Upload pr APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: build/app/outputs/apk/release/app-pr.apk
  # Setup Diffuse only when the two APKs are built successfully
  setup-diffuse:
    name: Setup diffuse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: git clone https://github.com/JakeWharton/diffuse.git
      - name: generate diffuse
        run: ./gradlew assemble
        working-directory: diffuse
      - name: Upload diffuse executable
        uses: actions/upload-artifact@v1
        with:
          name: diff
          path: diffuse/diffuse/build/diffuse
  # Execute Diffuse only when setup is successful
  diffuse:
    needs: [build-master, build-pr]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download APKs
        uses: actions/download-artifact@v1
        with:
          name: apk
      - name: Download diffuse executable
        uses: actions/download-artifact@v1
        with:
          name: diff
      - name: Change diffuse permissions
        run: |
            ls
            chmod +x ./diffuse
        working-directory: diff
      - name: Execute Diffuse
        run: ./diff/diffuse diff apk/app-master.apk apk/app-pr.apk
